### ISSUE TITLE
Typo "*@validate_subscriber_info*"→"*\@validate_subscriber_info*" 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/cognitive-toolkit-docs-python#66]
Italic with escape characters

https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms141934(v%3Dsql.105)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1331df62-f3fd-ec27-24e6-dd0b9b82679a
* Version Independent ID: c1727e5a-eba4-3402-4179-7fea0fae4c94
* Content: [cntk.ops.functions module](https://docs.microsoft.com/en-us/python/api/cntk/cntk.ops.functions?view=cntk-py-2.7)
* Content Source: [api-docs/cntk-2.7/docs-ref-autogen/cntk/cntk.ops.functions.yml](https://github.com/MicrosoftDocs/cognitive-toolkit-docs-python/blob/live/api-docs/cntk-2.7/docs-ref-autogen/cntk/cntk.ops.functions.yml)
* Service: **cognitive-toolkit**
* GitHub Login: @mahilleb-msft
* Microsoft Alias: **mahilleb**

**Comment by docs-product** [comment]
Hello @hyoshioka0128 - the feedback you provided is not applicable to CNTK content, therefore we cannot address it here. Additionally, the page you linked to is no longer supported or updated, therefore we won't be able to introduce any modifications there.
